- hosts: do-es-update-test
  remote_user: root
  # serial: 1
  roles:
    - role: firewall-off
    - role: elastic.elasticsearch
    - { role: elasticsearch_wait_green, es_http_port: 9200 }
  vars:
    es_instance_name: "{{ ansible_hostname }}"
    es_heap_size: "1g"
    es_enable_xpack: false
    es_allow_downgrades: true
    es_major_version: "5.x"
    es_version: "5.6.0"
    es_api_host: "0.0.0.0"
    es_api_port: 9200
    es_restart_on_change: false
    es_config:
      node.name: "{{ ansible_hostname }}"
      cluster.name: "es-update-test"
      discovery.zen.ping.unicast.hosts: '10.33.51.142:9300, 10.33.51.32:9300, 10.33.51.144:9300'
      discovery.zen.minimum_master_nodes: "2"
      network.bind_host: "0.0.0.0"
      network.host: "0.0.0.0"
      network.publish_host: "0.0.0.0"
      http.port: 9200
      transport.tcp.port: 9300
      node.master: true
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false

- hosts: front
  remote_user: root
  roles:
    - role: kibana
  vars:
    kibana_version: "5.6.10"
    kibana_index: ".kibana-5.6"
    kibana_server_port: 5601
    kibana_server_host: "0.0.0.0"
    kibana_elstic_url: "http://localhost:9200"